name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: build docker image and push to hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
          image: ollanoor/demonodeapp
          registry: docker.io
          dockerfile: Dockerfile
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_PASS }}"
          tags: latest
